version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: workSync_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - app-networks

  backend:
    build: ./backend
    container_name: workSync_backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/task_management
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    networks:
      - app-networks

  mongo:
    image: mongo:7.0
    container_name: workSync_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-networks

volumes:
  mongo_data:

networks:
  app-networks:
    driver: bridge
